pipeline {
    agent any

    environment {
        APP_NAME = "sample-app"
        DOCKER_IMAGE = "kepulupradeep/sample-app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                dir('my-app') {
                git branch: 'dev',
                    url: 'https://github.com/kepulupradeep/microdegree-2710.git'
            }
        }
        }

        stage('Build') {
            steps {
                echo "Building application..."
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                sh 'mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh 'docker build -t $DOCKER_IMAGE:latest .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-password', variable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u your-dockerhub-username --password-stdin
                        docker push $DOCKER_IMAGE:latest
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying application..."
                sh '''
                    docker stop sample-app || true
                    docker rm sample-app || true
                    docker run -d -p 8080:8080 --name sample-app $DOCKER_IMAGE:latest
                '''
            }
        }
    }

    post {
        success {
            echo "✅ CI/CD Pipeline executed successfully"
        }
        failure {
            echo "❌ CI/CD Pipeline failed"
        }
        always {
            echo "📌 Pipeline finished"
        }
    }
}
